In [13]:
import numpy as np
x = np.array([3, 5, 6, 9])
y = np.array([2, 5, 3, 10])
print("array elements:")
print(x)
print(y)
print("greater than:  ",end="")
print(np.greater(x, y))
print("greater equal: ",end="")
print(np.greater_equal(x, y))
print("less than:   ",end="")
print(np.less(x, y))
print("less equal:",end="")
print(np.less_equal(x, y))

array elements:
[3 5 6 9]
[ 2  5  3 10]
greater than:  [ True False  True False]
greater equal: [ True  True  True False]
less than:   [False False False  True]
less equal:[False  True False  True]


In [16]:
import numpy as np
print(np.arange(30,71,2))


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [25]:
import numpy as np
array=np.identity(3)
print('3x3 matrix:')
print(array)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
import numpy as np
x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of numbers in the range 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of numbers in the range 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [26]:
import numpy as np
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [31]:
import numpy as np
x = np.array([[2,1],[4,8]])
print("array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of column  elements:")
print(np.sum(x, axis=0))
print("Sum of row elements:")
print(np.sum(x, axis=1))

array:
[[2 1]
 [4 8]]
Sum of all elements:
15
Sum of column  elements:
[6 9]
Sum of row elements:
[ 3 12]


In [60]:
import numpy as np
import os
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
np.savetxt('temp.txt', x, fmt="%d") 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [57]:
import numpy as np
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.499, 1.5000, 0.2])
np.set_printoptions(precision=10)
print("arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal or not:?")
print(nums1 == nums2)


arrays:
[0.5 1.5 0.2]
[0.499 1.5   0.2  ]

Test said two arrays are equal or not:?
[False  True  True]


In [62]:
import numpy as np 
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nNew array after swapping first and last rows of the said array:")
nums[[0,3]]=nums[[3,0]]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [59]:
import numpy as np 
nums1 = np.array([[6, 7, 2],
              [1, 3, 4]])
nums2 = np.array([[8, 3, 1],
              [3, 9, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nMultiply said arrays of same size element-by-element:")
print(np.multiply(nums1, nums2))

Array1:
[[6 7 2]
 [1 3 4]]
Array2:
[[8 3 1]
 [3 9 5]]

Multiply said arrays of same size element-by-element:
[[48 21  2]
 [ 3 27 20]]
