In [20]:
    import numpy as np
    array1 = []
    a = int(input("no.of rows in the matrix:"))
    b = int(input("no.of columns in the matrix:"))
    for i in range(a*b):
        array1. append(float(input("Element:")))
    array1 = np. array(array1).reshape(a,b)
    print(np. floor(array1))
    array2 = []
    c = int(input("no.of rows in the matrix:"))
    d = int(input("no.of columns in the matrix:"))
 
    for i in range(c*d):
        array2. append(float(input("Element:")))
    array2 = np. array(array2).reshape(c,d)
    print(np. floor(array2))
    print("dot product:", np.dot(array1, array2))
    print("Transpose of 1st array:")
    print(np.transpose(array1))
    print("Transpose of 2nd array:")
    print(np.transpose(array2))
    print("Trace of 1st matrix: ")
    print(array1.trace())
    print("Trace of 2nd matrix: ")
    print(array2.trace())
    print("rank of 1st matrix: ")
    print(np.linalg.matrix_rank(array1))
    print("rank of 2nd matrix: ")
    print(np.linalg.matrix_rank(array2))
    print("determinant of 1st matrix: ")
    print(round(np.linalg.det(array1)))
    print("determinant of 2nd matrix: ")
    print(round(np.linalg.det(array2)))
    print("inverse of 1st matrix: ")
    print(np.linalg.inv(array1))
    print("inverse of 2nd matrix: ")
    print(np.linalg.inv(array2))
    print("eigen values and eigen vectors of 1st matrix: ")
    print(np.linalg.eig(array1))
    print("eigen values and eigen vectors  of 2nd matrix: ")
    print(np.linalg.eig(array2))

no.of rows in the matrix:2
no.of columns in the matrix:2
Element:1
Element:4
Element:5
Element:2
[[1. 4.]
 [5. 2.]]
no.of rows in the matrix:2
no.of columns in the matrix:2
Element:2
Element:5
Element:6
Element:3
[[2. 5.]
 [6. 3.]]
dot product: [[26. 17.]
 [22. 31.]]
Transpose of 1st array:
[[1. 5.]
 [4. 2.]]
Transpose of 2nd array:
[[2. 6.]
 [5. 3.]]
Trace of 1st matrix: 
3.0
Trace of 2nd matrix: 
5.0
rank of 1st matrix: 
2
rank of 2nd matrix: 
2
determinant of 1st matrix: 
-18
determinant of 2nd matrix: 
-24
inverse of 1st matrix: 
[[-0.11111111  0.22222222]
 [ 0.27777778 -0.05555556]]
inverse of 2nd matrix: 
[[-0.125       0.20833333]
 [ 0.25       -0.08333333]]
eigen values and eigen vectors of 1st matrix: 
(array([-3.,  6.]), array([[-0.70710678, -0.62469505],
       [ 0.70710678, -0.78086881]]))
eigen values and eigen vectors  of 2nd matrix: 
(array([-3.,  8.]), array([[-0.70710678, -0.6401844 ],
       [ 0.70710678, -0.76822128]]))
